### ISSUE TITLE
:feature request: Show line of the code that call the database query

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [nepalez/rspec-sqlimit#25]
Is there some way to show line of the code that call the database query?

**Comment by nepalez** [comment]
Hi @PedroAugustoRamalhoDuarte !

I don't think it is possible. The obvious reason for this is because the line of code that actually sends a request to the database server is digged deeply under layers of the ActiveRecord library. I won't be surprized if it is exactly the same line for most requests.

To restore the line where some finalizing method has been sent we would need to go up by the call stack from the place the notification is fired analyzing every method until we decide "this is the LOC we're interested about". This would be a big deal IMO.

**Comment by PedroAugustoRamalhoDuarte** [comment]
@nepalez Ok, i understand, thanks for the response!!
